---
- name: Satellite Setup on RHEL 9
  when:
    - satellite_enroll
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "9"
  ansible.builtin.shell: "{{ satellite_rhel_9_cmd  }}"

- name: Satellite Setup on RHEL 8
  when:
    - satellite_enroll
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "8"
  ansible.builtin.shell: "{{ satellite_rhel_8_cmd  }}"
  
- name: Regular Repo Setup
  when:
    - not satellite_enroll
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "8" or "9"
  ansible.builtin.template:
    src: templates/edb.j2
    dest: /etc/yum.repos.d/enterprisedb-edb.repo
    backup: true
